In [1]:
import numpy as np

a = np.eye(5)
print("Ma trận đơn vị 5x5:\n", a)
rank_a = np.linalg.matrix_rank(a)
print("Rank của ma trận đơn vị 5x5:", rank_a, "\n")

b = np.eye(3)
print("Ma trận đơn vị 3x3:\n", b)
rank_b = np.linalg.matrix_rank(b)
print("Rank của ma trận đơn vị 3x3:", rank_b)

Ma trận đơn vị 5x5:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Rank của ma trận đơn vị 5x5: 5 

Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Rank của ma trận đơn vị 3x3: 3
