In [15]:
import numpy as np
a = np.matrix(((1,-3,5), (4,5,-1), (-1,5,-9)))
print("Ma trận A 3x3:\n", a, "\n")

b = np.matrix(((10,-8,9), (-4,0,5), (1,3,4)))
print("Ma trận A 3x3:\n", b, "\n")

print("Tổng ma trận a và b:\n", a+b, "\n")
print("Tích ma trận a và b:\n", a*b, "\n")
print("Hiệu ma trận a và b:\n", a-b)

Ma trận A 3x3:
 [[ 1 -3  5]
 [ 4  5 -1]
 [-1  5 -9]] 

Ma trận A 3x3:
 [[10 -8  9]
 [-4  0  5]
 [ 1  3  4]] 

Tổng ma trận a và b:
 [[ 11 -11  14]
 [  0   5   4]
 [  0   8  -5]] 

Tích ma trận a và b:
 [[ 27   7  14]
 [ 19 -35  57]
 [-39 -19 -20]] 

Hiệu ma trận a và b:
 [[ -9   5  -4]
 [  8   5  -6]
 [ -2   2 -13]]
