In [24]:
import numpy as np

a = np.random.randint(10, size = (5,5))

# convert array a to maxtrix a
matrix_a = np.matrix(a)

print("Ma trận ngẫu nhiên a:\n",matrix_a)
print("Tổng của đường chéo chính:", np.sum(np.diag(maxtrix_a, 0)))
print("Đường chéo phụ thứ k = 1:", np.diag(matrix_a, 1))
print("Đường chéo phụ thứ k = -1:", np.diag(matrix_a, -1))

Ma trận ngẫu nhiên a:
 [[3 4 1 2 2]
 [4 0 8 3 6]
 [4 0 3 2 4]
 [4 5 1 0 5]
 [3 0 8 3 3]]
Tổng của đường chéo chính: 17
Đường chéo phụ thứ k = 1: [4 8 2 5]
Đường chéo phụ thứ k = -1: [4 0 1 3]
