In [86]:
import numpy as np

x = np.matrix([[ 2,3,4,5,1], [2, -1, 2, -3, -1], [3, 4, -6, 7, 1]])

print("Ma trận x:\n", x, "\n")
print("1. In dòng thứ 2:\n", x[1], "\n")
print("2. In cột thứ 3:\n", x[:, 2], "\n")
print("3. In tất cả các hàng và cột thứ 1 đến cột thứ 4:\n", x[:, :4], "\n")
print("4. In 2 hàng đầu và 3 cột đầu:\n", x[:2, :3], "\n")
print("5. Giá trị lớn nhất:", np.max(x), "\n")
print("5.1 Giá trị nhỏ nhất:", np.min(x), "\n")
print("6. Index max của hàng 3:", np.argmax(x[2]), "\n")
print("6.1. Index min của hàng 3:", np.argmin(x[2]), "\n")
try:
    print("7. Index max của dòng 4:", np.argmax(x[3]), "\n")
    print("7.1. Index min của dòng 4:", np.argmin(x[3]), "\n")
except:
    print("7. Ma trận x chỉ có 3 hàng(dòng)", "\n")
print("8. Độ lệch chuẩn:", np.std(x), "\n")
print("9. Độ lệch chuẩn của cột:\n", np.std(x, 1), "\n")
print("10. Độ lệch chuẩn của hàng:\n", np.std(x, 0))

Ma trận x:
 [[ 2  3  4  5  1]
 [ 2 -1  2 -3 -1]
 [ 3  4 -6  7  1]] 

1. In dòng thứ 2:
 [[ 2 -1  2 -3 -1]] 

2. In cột thứ 3:
 [[ 4]
 [ 2]
 [-6]] 

3. In tất cả các hàng và cột thứ 1 đến cột thứ 4:
 [[ 2  3  4  5]
 [ 2 -1  2 -3]
 [ 3  4 -6  7]] 

4. In 2 hàng đầu và 3 cột đầu:
 [[ 2  3  4]
 [ 2 -1  2]] 

5. Giá trị lớn nhất: 7 

5.1 Giá trị nhỏ nhất: -6 

6. Index max của hàng 3: 3 

6.1. Index min của hàng 3: 2 

7. Ma trận x chỉ có 3 hàng(dòng) 

8. Độ lệch chuẩn: 3.159465496286076 

9. Độ lệch chuẩn của cột:
 [[1.41421356]
 [1.93907194]
 [4.35430821]] 

10. Độ lệch chuẩn của hàng:
 [[0.47140452 2.1602469  4.3204938  4.3204938  0.94280904]]
