In [26]:
import numpy as np
from numpy import linalg

a = np.matrix(((-1, 4, 7, 4), (7, 5, 2, 0), (-4, 5, 9, 1), (-8, -6, 5, 3)))

print("Ma trận a:\n", a, "\n")
print("1. Định thức của ma trận a:", np.linalg.det(a), "\n")
x, v = linalg.eig(np.array(a))
print("1.1 Trị riêng của ma trận a:\n", x, "\n")
print("1.2 Vector riêng của ma trận a:\n", v, "\n")
print("2. Ma trận nghịch đạo của ma trận a:\n", linalg.inv(a), "\n")
print("3. Ma trận chuyển vị của ma trận a:\n", np.transpose(a))

Ma trận a:
 [[-1  4  7  4]
 [ 7  5  2  0]
 [-4  5  9  1]
 [-8 -6  5  3]] 

1. Định thức của ma trận a: -1230.9999999999993 

1.1 Trị riêng của ma trận a:
 [-2.293435  +0.j          3.64252074+5.95736883j  3.64252074-5.95736883j
 11.00839353+0.j        ] 

1.2 Vector riêng của ma trận a:
 [[-0.49644034+0.j         -0.25448684+0.27282042j -0.25448684-0.27282042j
   0.35891527+0.j        ]
 [ 0.60802132+0.j          0.31830532+0.26933036j  0.31830532-0.26933036j
   0.59843265+0.j        ]
 [-0.47974078+0.j         -0.12759263-0.18954556j -0.12759263+0.18954556j
   0.541606  +0.j        ]
 [ 0.39205338+0.j         -0.79670631+0.j         -0.79670631-0.j
  -0.46874421+0.j        ]] 

2. Ma trận nghịch đạo của ma trận a:
 [[-0.05523964  0.20877335 -0.05442729  0.09179529]
 [ 0.13160032 -0.1738424   0.04142973 -0.18927701]
 [-0.13566206  0.20389927  0.0869212   0.15190902]
 [ 0.34199838 -0.13078798 -0.20714866 -0.05361495]] 

3. Ma trận chuyển vị của ma trận a:
 [[-1  7 -4 -8]
 [ 4  5  5 -6]
