In [26]:
import numpy as np
# shape (2,2,3)
array1 = np.full((2,2,3), 8)
print("Shape (2, 3, 3): \n", array1)
print("------------------")

array2 = np.full((2,1,3), 9)
print("Shape (2, 1, 3): \n", array2)
print("------------------")

array3 = np.full((3,2,3), 8)
print("Shape (3, 2, 3): \n", array3)
print("------------------")


Shape (2, 3, 3): 
 [[[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]]
------------------
Shape (2, 1, 3): 
 [[[9 9 9]]

 [[9 9 9]]]
------------------
Shape (3, 2, 3): 
 [[[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]]
------------------
