In [21]:
# shape (2, 3, 5)
import numpy as np
import random

array1 = np.random.random((2, 3, 5))
print("Shape (2, 3, 5): \n", array1)
print("------------------------")

array2 = np.random.randint(1, 10, size = (3, 4, 2))
print("Shape with rule (3, 4, 2): \n", array2)

Shape (2, 3, 5): 
 [[[0.98572534 0.77168362 0.84186144 0.30150026 0.95039966]
  [0.78334247 0.37160832 0.26094864 0.43986415 0.43577525]
  [0.59148367 0.73159736 0.06025293 0.36019888 0.21079724]]

 [[0.4639624  0.9009038  0.29132058 0.8034707  0.41006053]
  [0.56073403 0.30433214 0.35091211 0.919799   0.18521465]
  [0.29687116 0.0145046  0.57172792 0.69007176 0.71862751]]]
------------------------
Shape with rule (3, 4, 2): 
 [[[5 4]
  [4 5]
  [3 7]
  [1 6]]

 [[5 7]
  [7 7]
  [4 9]
  [9 9]]

 [[6 8]
  [1 8]
  [9 5]
  [7 6]]]
