In [8]:
import numpy as np
import random
array1 = np.random.randint(2, 13, size = (2, 3, 5))
print("Array with range(2, 13) and shape (2,3,5): \n", array1)

Array with range(2, 13) and shape (2,3,5): 
 [[[ 8  6  8  4 12]
  [ 6  4  9 11  9]
  [ 9  4 11  9  6]]

 [[11  2 11  4 11]
  [12  3  4 11  3]
  [ 7  9  6  9  9]]]
